server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/green?serverTimezone=Asia/Seoul&charactorEncoding=UTF-8
    username: root
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
kakao:
  api:
    key: "c70330a63c2c9574a93ab5077435c3e4"
    authUri: "https://kauth.kakao.com/oauth"
    redirectUri: "http://localhost:8080/oauth/kakao"